config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :thoughts

  ActiveAdmin.routes(self)

  root to: redirect('/thoughts')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reference.rb
class Reference < ApplicationRecord
  has_many :thoughts, dependent: :destroy
end

app/models/source.rb
class Source < ApplicationRecord
  has_many :thoughts, dependent: :destroy
end

app/models/thought.rb
class Thought < ApplicationRecord
  belongs_to :source
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    elsif
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  before_action :set_thought, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /thoughts
  # GET /thoughts.json
  def index
    @thoughts = Thought.all
  end

  # GET /thoughts/1
  # GET /thoughts/1.json
  def show
  end

  # GET /thoughts/new
  def new
    @thought = Thought.new
  end

  # GET /thoughts/1/edit
  def edit
  end

  # POST /thoughts
  # POST /thoughts.json
  def create
    @thought = Thought.new(thought_params)

    respond_to do |format|
      if @thought.save
        format.html { redirect_to @thought, notice: 'Thought was successfully created.' }
        format.json { render :show, status: :created, location: @thought }
      else
        format.html { render :new }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thoughts/1
  # PATCH/PUT /thoughts/1.json
  def update
    respond_to do |format|
      if @thought.update(thought_params)
        format.html { redirect_to @thought, notice: 'Thought was successfully updated.' }
        format.json { render :show, status: :ok, location: @thought }
      else
        format.html { render :edit }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thoughts/1
  # DELETE /thoughts/1.json
  def destroy
    @thought.destroy
    respond_to do |format|
      format.html { redirect_to thoughts_url, notice: 'Thought was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thought
      @thought = Thought.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thought_params
      params.require(:thought).permit(:content, :position)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Danao</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if current_user.present? %>
        <%= current_user.name %>,
        <%= current_user.email %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% else %>
        <!%= link_to 'Login', login_path %>
        <!%= link_to 'Register', register_path %>
      <% end %>
    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/thoughts/_form.html.erb
<%= form_with(model: thought, local: true) do |form| %>
  <% if thought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thought.errors.count, "error") %> prohibited this thought from being saved:</h2>

      <ul>
      <% thought.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/thoughts/edit.html.erb
<h1>Editing Thought</h1>

<%= render 'form', thought: @thought %>

<%= link_to 'Show', @thought %> |
<%= link_to 'Back', thoughts_path %>

app/views/thoughts/index.html.erb
<h1>Thoughts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thoughts.each do |thought| %>
      <tr>
        <td><%= thought.content %></td>
        <td><%= thought.position %></td>
        <td><%= link_to 'Show', thought %></td>
        <td><%= link_to 'Edit', edit_thought_path(thought) %></td>
        <td><%= link_to 'Destroy', thought, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thought', new_thought_path %>

app/views/thoughts/new.html.erb
<h1>New Thought</h1>

<%= render 'form', thought: @thought %>

<%= link_to 'Back', thoughts_path %>

app/views/thoughts/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @thought.content %>
</p>

<p>
  <strong>Position:</strong>
  <%= @thought.position %>
</p>

<%= link_to 'Edit', edit_thought_path(@thought) %> |
<%= link_to 'Back', thoughts_path %>

app/views/users/new.html.erb
<h1>
  Register
</h1>

<%= form_for :user do |f| %>
  <%= f.label :email, 'Email' %>
  <%= f.text_field :email %>

  <%= f.label :name, 'Name' %>
  <%= f.text_field :name %>

  <%= f.label :password, 'Password' %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, 'Confirm password' %>
  <%= f.password_field :password_confirmation %>

  <div>
    <%= f.submit 'Register' %>
  </div>
<% end %>